cc_binary(
    name = 'raftlog',
    srcs = 'raftlog.cc',
    deps = [
        '//raft:raft_proto',
        '//raft:raft',
        '//thirdparty/gflags:gflags',
        '//thirdparty/muduo:muduo_base'
    ]
)
